import type { Metadata } from "next";
import "./globals.css";
import { lekton, lektonBold } from "./font/fonts";
import { NextThemeProvider } from "./providers/themeProvider";
import ReactQueryProvider from "./providers/react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="kr"
      className={`${lekton.variable} ${lektonBold.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="font-regular">
        <NextThemeProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
