import { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "playground server aciton with react query",
  description: "Generated by Hank",
};

export default function Layout({ children }: PropsWithChildren<{}>) {
  return <div className={inter.className}>{children}</div>;
}
